name       : geonkick
version    : 2.2.3
release    : 7
source     :
    - https://github.com/iurie-sw/geonkick/archive/v2.2.3.tar.gz : 8fba21e6547c426f852927666610bbd65a357cbc21e8893279cbd6b27053e4cd
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A free software percussion synthesizer
description: |
    Geonkick is a synthesizer that can synthesize elements of percussion. The most basic examples are: kicks, snares, hit-hats, shakers, claps, sticks. Also, it can play samples.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(jack)
    - pkgconfig(lv2)
    - pkgconfig(sndfile)
    - pkgconfig(x11)
    - rapidjson-devel
    - redkite-devel
setup      : |
    %cmake_ninja -DGKICK_REDKITE_SDK_PATH=/usr
build      : |
    %ninja_build
install    : |
    %ninja_install
