name       : geonkick
version    : 2.3.2
release    : 8
source     :
    - https://github.com/iurie-sw/geonkick/archive/v2.3.2.tar.gz : 8952ac8497d6b238befa91391155b8bd1f9ef8bf41452f15a34a36a3417aea39
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A free software percussion synthesizer
description: |
    Geonkick is a synthesizer that can synthesize elements of percussion. The most basic examples are: kicks, snares, hit-hats, shakers, claps, sticks. Also, it can play samples.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(jack)
    - pkgconfig(lv2)
    - pkgconfig(sndfile)
    - pkgconfig(x11)
    - rapidjson-devel
    - redkite-devel
setup      : |
    %cmake_ninja -DGKICK_REDKITE_SDK_PATH=/usr
build      : |
    %ninja_build
install    : |
    %ninja_install
