name       : geonkick
version    : 2.3.8
release    : 11
source     :
    - https://github.com/iurie-sw/geonkick/archive/v2.3.8.tar.gz : 19e9a58de4ec28c5ecb59c02b172a7d68ac27b0d0d907759dca3f8b10e0eab6f
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A free software percussion synthesizer
description: |
    Geonkick is a synthesizer that can synthesize elements of percussion. The most basic examples are: kicks, snares, hit-hats, shakers, claps, sticks. Also, it can play samples.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(jack)
    - pkgconfig(lv2)
    - pkgconfig(sndfile)
    - pkgconfig(x11)
    - rapidjson-devel
    - redkite-devel
setup      : |
    %cmake_ninja -DGKICK_REDKITE_SDK_PATH=/usr
build      : |
    %ninja_build
install    : |
    %ninja_install
