name       : geonkick
version    : 2.6.1
release    : 13
source     :
    - https://github.com/iurie-sw/geonkick/archive/v2.6.1.tar.gz : e060f9bf42254b3f755ebcd62bec1279bf0e151c5442d1cf68dbb44fb9ef9152
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : A free software percussion synthesizer
description: |
    Geonkick is a synthesizer that can synthesize elements of percussion. The most basic examples are: kicks, snares, hit-hats, shakers, claps, sticks. Also, it can play samples.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(jack)
    - pkgconfig(lv2)
    - pkgconfig(sndfile)
    - pkgconfig(x11)
    - rapidjson-devel
    - redkite-devel
setup      : |
    %cmake_ninja -DGKICK_REDKITE_SDK_PATH=/usr
build      : |
    %ninja_build
install    : |
    %ninja_install
